substitutions:
  name: "sensor-pkg-a-ld2410"
  friendly_name: "Sensor Pkg A Radar LD2410"

  # Settings
  use_pir_in_presence: "true"
  # Status LED configuration
  status_day_brightness: "0.5"
  status_night_brightness: "0.20"
  status_daytime_lux: "12.0"
  status_nighttime_lux: "7.0"
  # CO configuration
  co_temp_id: "temperature"
  co_offset: "0.0"
  co_sensitivity: "2.000e-9"
  co_manufacture_date: "01/01/1999"
  co_serial_number: "111111111111111111"
  # SEN6X Configuration
  sen6x_temperature_offset: "0.0"
  sen6x_humidity_offset: "0.0"
  sen6x_output_rate: "60s"
  # INA2XX Configuration
  INA2XX_output_rate: "60s"
  # Automatically controlled Vent
  vent_ha_entity: fan.vent_id
  vent_use_humidity: "true"
  vent_use_co2: "true"
  vent_min_on_time: "15"
  vent_hum_on_trigger: "10.0"
  vent_hum_off_trigger: "2.5"
  vent_co2_on_trigger: "1100"
  vent_co2_off_trigger: "900"

packages:
  # COMMON
  common: !include common/common.yaml

  # SENSORS - PACKAGE A - Sensirion SEN66
  sen6x_pkga: !include common/pkga-sen6x.yaml

  # MMWAVE SENSOR - Hi-Link LD2410
  ld2410_radar: !include common/radar-ld2410.yaml

  # ADDITIONAL SENSORS
  # Carbon Dioxide (CO) - Figaro TGS5141 sensor
  co_add: !include common/add-co.yaml
  # Energy Usage - INA2XX sensor to measure Voltage, Power and Energy Usage
  ina2xx_add: !include common/add-ina2xx.yaml
  # Light Level - TSL2591 sensor
  tsl2591_add: !include common/add-tsl2591.yaml
  # Barometric Pressure - BMP581 sensor
  bmp581_add: !include common/add-bmp581.yaml
  # Speaker - Adds audio output and Media Player
  speaker_add: !include common/add-speaker.yaml
  # Microphone - Adds Sound Level meter
  microphone_add: !include common/add-microphone.yaml

  # FEATURES
  # SEN6X Pressure Compensation
  sen6x_pres_comp_feat: !include common/feat-sen6x-press-comp.yaml
  # Automatic Vent - Use humidity and CO₂ control a bathroom vent
  # auto_vent_feat:       !include common/feat-auto-vent.yaml

api:

external_components:
  - source: github://mikelawrence/esphome-components@main
    components: [sen5x, bmp581]

dashboard_import:
  package_import_url: github://mikelawrence/ESPHome-Multi-Test/config/pkg-a-radar-ld2410.yaml@main
  import_full_config: true

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
